### PR TITLE
Update scitypes.jl

### PR DESCRIPTION
**Pull request by OkonSamuel**
Addresses [ScientificTypes.jl#179](https://github.com/JuliaAI/ScientificTypes.jl/issues/179)

### CODE REVIEW

**Comment by juliohm** [comment]
So we should only depend on ScientificTypesBase.jl now @OkonSamuel ?

**Comment by OkonSamuel** [comment]
> So we should only depend on ScientificTypesBase.jl now @OkonSamuel ?

Yes. Only extend methods from `ScientificTypesBase`. But you would still need to import `ScientificTypes` to use `scitype(c)`
```julia
julia> using CoDa, ScientificTypes

julia> c = Composition(1,2,3)
                  3-part composition
      ┌                                        ┐
   w1 ┤■■■■■■■■■■■■ 1.0
   w2 ┤■■■■■■■■■■■■■■■■■■■■■■■ 2.0
   w3 ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 3.0
      └                                        ┘

julia> scitype(c)
Compositional{3}
```

**Comment by juliohm** [comment]
But it seems that we still need DefaultConvention from ScientificTypes.jl? It is a bit confusing. Can you please clarify?

**Comment by OkonSamuel** [comment]
> But it seems that we still need DefaultConvention from ScientificTypes.jl? It is a bit confusing. Can you please clarify?

Yes, You would still need `ScientificTypes`, `DefaultConvention`.

So that could be done by 
```julia
ST.ScientificTypesBase.scitype(::YourType, ::ST.DefaultConvention) = ...
```
I hope this is clear enough.

**Comment by juliohm** [comment]
I find it strange that ScientificTypes.jl doesn't reexport scitype from ScientificTypesBase.jl. Someone depending on the default convention would like to implement methods for functions defined in the same module. Any chance these functions can be reexported in ScientificTypes.jl? I really feel that we should try another round of refactoring in these two packages.

**Comment by OkonSamuel** [comment]
> I find it strange that ScientificTypes.jl doesn't reexport scitype from ScientificTypesBase.jl. Someone depending on the default convention would like to implement methods for functions defined in the same module. Any chance these functions can be reexported in ScientificTypes.jl? I really feel that we should try another round of refactoring in these two packages.

I'll discuss with @ablaom about this possibility.

**Comment by OkonSamuel** [comment]
@juliohm what if I renamed the `scitype` method from `ScientificTypesBase` as `scitype_def` and exported that?
So you could do
```julia
using CoDa, ScientificTypes

ScientificTypes.scitype_def(::YourType, ::ST.DefaultConvention) = ...

c = Composition(1,2,3)

scitype(c)
```

**Comment by juliohm** [comment]
Why do we need two different function names @OkonSamuel ? Isn't just a single function with multiple methods we are discussing? Something changed recently? Why things are split between two packages the way they are?

**Comment by OkonSamuel** [comment]
> Why do we need two different function names @OkonSamuel ? Isn't just a single function with multiple methods we are discussing? Something changed recently? Why things are split between two packages the way they are?

Yes, there was a recent change as regards performance, we wanted to avoid setting convention at run time.

We can't just move the `DefaultConvention` implemted in `ScientificTypes` to `ScientificTypesBase.jl` because we wish that `ScientificTypesBase.jl` be as light as possible.

**Pull request merged**
